### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/churnado#2]
These are a few resources about churn prediction.

### Classical Machine Learning
- [Predict Customer Churn – Logistic Regression, Decision Tree and Random Forest](https://datascienceplus.com/predict-customer-churn-logistic-regression-decision-tree-and-random-forest/)
- [A Simple Approach to Predicting Customer Churn](http://blog.keyrus.co.uk/a_simple_approach_to_predicting_customer_churn.html)
- [Predicting Email Churn with NBD/Pareto](https://www.blendo.co/blog/predicting-email-churn-nbd-pareto/). Uses a statistical distribution to do the predictions.

### Neural Networks
- [Deep Learning With Keras To Predict Customer Churn](https://tensorflow.rstudio.com/blog/keras-customer-churn.html). Basic churn prediction with Keras in R. Interesting as a starting point and it also uses LIME.
- [Predicting Azure Churn with Deep Learning and Explaining Predictions with LIME](https://www.slideshare.net/FengZhu18/predicting-azure-churn-with-deep-learning-and-explaining-predictions-with-lime). Love this approach as it merges features with events. We can always add a new branch with other approaches like WTTE-RNN. **I think this is the best approach for our case so far.**
- [Deep Learning for Customer Churn Prediction](https://webcache.googleusercontent.com/search?q=cache:9MTd_SSnELgJ:https://moz.com/devblog/deep-learning-for-customer-churn-prediction/+&cd=1&hl=en&ct=clnk&gl=es)
- [WTTE-RNN - Less hacky churn prediction](https://ragulpr.github.io/2016/12/22/WTTE-RNN-Hackless-churn-modeling/). A lot of interesting ideas here. Definitely something we could try in the future!

**Comment by jwinternheimer** [comment]
Whoa, this is awesome! Thanks @davidgasquez 🔖
