### ISSUE TITLE
Project template

### ISSUE THREAD

**Issue by jwinternheimer** [bufferapp/churnado#5]
We should have a standard one, like this: https://github.com/michael-erasmus/cookiecutter-data-science/tree/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D 😄

**Comment by davidgasquez** [comment]
True! Working on it right now. :wink:

**Comment by davidgasquez** [comment]
Also, they have a really good [_Opinions_ section in their docs](https://drivendata.github.io/cookiecutter-data-science/#opinions). Worth reading and sharing!

**Comment by davidgasquez** [comment]
Closing this as we're now inline with the project template. We can keep adding folders as we go!

**Comment by jwinternheimer** [comment]
You rock! 💥
